//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatexDocumentExample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci tortor, tempus at vulputate vel, cursus vitae quam. Aliquam tincidunt eget odio id posuere. Donec rhoncus consectetur erat, sed tempus erat interdum a. Aliquam dictum imperdiet massa non vestibulum. Quisque rutrum ligula non nisl maximus fringilla. Proin condimentum fermentum accumsan. Morbi venenatis eros sed mi fermentum efficitur. Donec auctor, diam nec gravida egestas, magna libero interdum enim, at venenatis justo libero sed lectus. Nullam lectus nibh, porttitor ut turpis cursus, eleifend iaculis augue. Vivamus mollis, eros nec sagittis accumsan, quam ipsum hendrerit erat, eget fringilla ante nunc sed metus. Sed hendrerit dui ut ultrices faucibus. Nulla velit turpis, pretium a nibh sit amet, dapibus suscipit magna. Sed feugiat a sapien vitae pellentesque. Nam et dolor nec magna ultrices lobortis. Nulla gravida lobortis magna bibendum volutpat.")]
        public string LoremIpsum {
            get {
                return ((string)(this["LoremIpsum"]));
            }
            set {
                this["LoremIpsum"] = value;
            }
        }
    }
}
